version: "3.9"

services:
    django:
        build:
            context: .
            dockerfile: Dockerfile
        command: /bin/bash
        volumes:
            - .:/app
        network_mode: host
        depends_on:
            - rabbitmq
            - postgresql
        shm_size: 4gb
    rabbitmq:
        image: 'bitnami/rabbitmq:latest'
        network_mode: host
        environment:
            - RABBITMQ_VHOST=asyncdj
            - RABBITMQ_USERNAME=bugs
            - RABBITMQ_PASSWORD=passyword
    postgresql:
        image: postgis/postgis:15-master
        network_mode: host
        volumes:
            - "$HOME/pgdata/celery-weather-rabbitmq:/var/lib/postgresql/data"
        environment:
            - POSTGRES_DB=asyncdj
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=passyword
