services:
    django:
        build:
            context: .
            dockerfile: Dockerfile
        command: /bin/bash
        volumes:
            - .:/app
        ports:
          - 8000:8000
        depends_on:
            - rabbitmq
            - postgresql
        shm_size: 4gb
    rabbitmq:
        image: rabbitmq:3.12
        ports:
          - 5672
        environment:
            - RABBITMQ_DEFAULT_USER=bugs
            - RABBITMQ_DEFAULT_PASS=passyword
            - RABBITMQ_DEFAULT_VHOST=asyncdj
    postgresql:
        image: postgis/postgis:15-master
        ports:
          - 5432
        volumes:
            - "$HOME/pgdata/celery-weather-rabbitmq:/var/lib/postgresql/data"
        environment:
            - POSTGRES_DB=asyncdj
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=passyword
