# Generated by Django 4.2.7 on 2023-11-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djstorm', '0002_alter_weatherpoint_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherpoint',
            name='point',
            field=models.CharField(db_index=True, max_length=25),
        ),
    ]
