services:
    django:
        build:
            context: .
            dockerfile: Dockerfile
        command: /bin/bash
        volumes:
            - .:/app
        ports:
          - 8000:8000
        shm_size: 4gb
