version: "3.9"

services:
    django:
        build:
            context: .
            dockerfile: Dockerfile
        command: /bin/bash
        volumes:
            - .:/app
        network_mode: host
        shm_size: 4gb
