web: PYTHONUNBUFFERED=true uvicorn cweather.asgi:application --loop uvloop
worker: PYTHONUNBUFFERED=true celery -A cweather worker -l INFO -c 3
beat: PYTHONUNBUFFERED=true celery -A cweather beat -l INFO
